// ===== EDIT PRICES / ITEMS HERE =====
// Each dish is one line: name, desc, and price (or price + priceG for Normal/Grande, or price + priceMenu for Solo/Menú).
// To change a price, just edit the number in quotes, e.g. price:'7,00' -> price:'7,50'. No other code needs to change.
const MENU_DATA = [
  { key:'menus', label:'Menús', image:'https://images.pexels.com/photos/27703379/pexels-photo-27703379.jpeg?auto=compress&cs=tinysrgb&w=1200', imageAlt:'Menú combinado con patatas y bebida', note:'Cada menú incluye patatas fritas y bebida.', items:[
    {name:'Menú 1', desc:'1 kebab pita + patatas fritas + bebida 33cl', price:'7,00', priceG:'8,00'},
    {name:'Menú 2', desc:'1 dürüm + patatas fritas + bebida 33cl', price:'7,00', priceG:'8,00'},
    {name:'Menú 3', desc:'Plato de kebab con patatas, pan y ensalada + bebida', price:'8,00'},
    {name:'Menú 4', desc:'1 hamburguesa + patatas fritas + bebida 33cl', price:'7,00', priceG:'8,00'},
    {name:'Menú 5', desc:'1 pizza mediana + 1 kebab con todo + bebida 1L', price:'15,00'},
    {name:'Menú 6', desc:'3 kebabs de ternera + patatas fritas + bebida 1L', price:'17,00', priceG:'20,00'},
    {name:'Menú 7', desc:'4 kebabs de ternera + patatas fritas + bebida 1L', price:'22,00', priceG:'24,00'},
    {name:'Menú 8', desc:'2 kebabs pita de ternera + patatas fritas + bebida 1L', price:'13,00', priceG:'15,00'},
    {name:'Menú 9', desc:'1 pizza familiar + patatas fritas + bebida 1L', price:'17,00'},
    {name:'Menú 10', desc:'2 pizzas medianas + patatas fritas + bebida 1L', price:'17,00'},
    {name:'Menú 11', desc:'2 pizzas grandes + 1 pizza mediana + patatas fritas + bebida 1L', price:'25,00'},
    {name:'Menú 12', desc:'2 pizzas familiares + patatas + bebida 1L', price:'30,00'},
  ], orderable:true},
  { key:'kebab', label:'Kebab y Dürüm', image:'https://images.pexels.com/photos/24981551/pexels-photo-24981551.jpeg?auto=compress&cs=tinysrgb&w=1200', imageAlt:'Döner kebab recién cortado', groups:[
    { name:'Pita', items:[
      {name:'Döner normal', desc:'Pan, carne de ternera, pollo o mixto, ensalada y salsa', price:'5,00', priceG:'6,00'},
      {name:'Döner con queso', desc:'Pan, carne de ternera y salsa (pollo +0,50€)', price:'6,00', priceG:'7,00'},
      {name:'Döner vegetal', desc:'Pan, falafel, ensalada y salsa', price:'6,00', priceG:'7,00'},
      {name:'Döner solo carne', desc:'Pan, carne de ternera o pollo, ensalada y salsa', price:'6,00', priceG:'7,00'},
      {name:'Döner con patatas', desc:'Pan, carne de ternera o pollo, ensalada, patatas y salsa', price:'6,00', priceG:'7,00'},
      {name:'Döner especial', desc:'Pan, carne de ternera, pollo, ensalada y salsa', price:'6,00', priceG:'7,00'},
    ]},
    { name:'Dürüm', items:[
      {name:'Dürüm normal', desc:'Pan, carne de ternera, pollo o mixto, ensalada y salsa', price:'5,00', priceG:'6,00'},
      {name:'Dürüm solo carne', desc:'Pan, carne de ternera y salsa', price:'6,00', priceG:'7,00'},
      {name:'Dürüm con queso', desc:'Pan, carne de ternera y salsa (pollo +0,50€)', price:'6,00', priceG:'7,00'},
      {name:'Dürüm vegetal', desc:'Pan, falafel, ensalada, patatas y salsa', price:'6,00', priceG:'7,00'},
      {name:'Dürüm con patatas', desc:'Pan, carne de ternera o pollo, ensalada, patatas y salsa', price:'6,00', priceG:'7,00'},
      {name:'Dürüm especial', desc:'Pan, carne de ternera o pollo, ensalada, patatas y salsa', price:'6,00', priceG:'7,00'},
    ]},
  ]},
  { key:'platos', label:'Platos y Hamburguesa', image:'https://images.pexels.com/photos/70497/pexels-photo-70497.jpeg?auto=compress&cs=tinysrgb&w=1200', imageAlt:'Plato con patatas fritas', items:[
    {name:'Plato kebab', desc:'Carne de ternera, pollo o mixto, ensalada y patatas fritas', price:'7,00'},
    {name:'Plato con queso', desc:'Carne de ternera o pollo, queso, ensalada y patatas fritas', price:'8,00'},
    {name:'Plato vegetariano', desc:'Falafel, queso, ensalada y patatas fritas', price:'6,50'},
    {name:'Plato solo carne', desc:'Carne de ternera, queso, ensalada y patatas fritas', price:'8,50'},
    {name:'Plato con bacon y queso', desc:'Carne de ternera o pollo, bacon, queso y patatas fritas', price:'8,00'},
    {name:'Patatas al horno con bacon y queso', desc:'', price:'8,00'},
    {name:'Hamburguesa normal', desc:'Lechuga, tomate, pollo o ternera, huevo y queso', price:'5,00', priceG:'6,00'},
  ]},
  { key:'pizzas', label:'Pizzas', image:'https://images.pexels.com/photos/9993754/pexels-photo-9993754.jpeg?auto=compress&cs=tinysrgb&w=1200', imageAlt:'Pizza recién horneada con queso fundido', note:'Normal 8,00€ · Grande 10,00€ · Familiar 15,00€ (consulta suplemento en pizzas más cargadas)', items:[
    {name:'Margarita', desc:'Tomate, queso y orégano'},
    {name:'Vegetariana', desc:'Tomate, queso, pimiento verde y rojo, cebolla, champiñón, maíz, olivas y orégano'},
    {name:'Mexicana', desc:'Tomate, queso, carne picada, champiñón, maíz y orégano'},
    {name:'Hawaiana', desc:'Tomate, queso, jamón y piña'},
    {name:'Caprichosa', desc:'Tomate, queso, jamón, champiñones, olivas y huevo'},
    {name:'Tono atún', desc:'Tomate, queso, atún, cebolla, ajo, olivas y orégano'},
    {name:'Roma', desc:'Tomate, queso, jamón, champiñones y orégano'},
    {name:'Jamón y queso', desc:'Tomate, queso, jamón y orégano'},
    {name:'Cuatro quesos', desc:'Tomate, cuatro quesos y orégano'},
    {name:'Barbacoa', desc:'Tomate, pollo, ternera y salsa barbacoa'},
    {name:'Barbacoa Tex', desc:'Tomate, queso, jamón york, ternera y salsa barbacoa'},
    {name:'Barbacoa 2', desc:'Tomate, pollo, bacon, salsa barbacoa, carne picada y orégano'},
    {name:'Super pizza', desc:'Tomate, pollo, bacon, carne picada, champiñones, cebolla y orégano'},
    {name:'Carbonara', desc:'Tomate, queso, champiñones y orégano'},
    {name:'Bacon tomate', desc:'Tomate, nata, bacon, huevo, cebolla y orégano'},
    {name:'Carne picada', desc:'Tomate, queso y carne picada'},
    {name:'Al gusto', desc:'Tomate, queso y 2 ingredientes a elegir'},
    {name:'Döner kebab', desc:'Tomate, queso, carne asada, ajo y cebolla'},
    {name:'Miramare', desc:'Tomate, queso, champiñones, jamón york, gambas y orégano'},
    {name:'Napoli', desc:'Tomate, queso mozzarella, jamón york y anchoas'},
    {name:'Tikka', desc:'Brocheta de pollo, cebolla y orégano'},
    {name:'Toronto', desc:'Tomate, queso, salami, champiñón y orégano'},
    {name:'Calzone', desc:'Tomate, queso, salami, champiñón, jamón y orégano'},
    {name:'Pepperoni', desc:'Tomate, queso, pepperoni y orégano'},
    {name:'Salami', desc:'Tomate, queso, salami y orégano'},
    {name:'Super barbacoa', desc:'Tomate, queso, pollo, bacon, salsa barbacoa, champiñones, cebolla y orégano'},
    {name:'Super carbonara', desc:'Tomate, queso, salami, champiñón, jamón y orégano'},
    {name:'4 estaciones', desc:'Tomate, queso, chorizo picante, olivas negras, champiñones, salami, jamón, bacon, huevo y cebolla'},
    {name:'Picante', desc:'Salsa de tomate, queso, chorizo, salami, bacon, huevo, cebolla y orégano'},
  ]},
  { key:'tapas', label:'Tapas y Extras', image:'https://images.pexels.com/photos/6941009/pexels-photo-6941009.jpeg?auto=compress&cs=tinysrgb&w=1200', imageAlt:'Patatas fritas, nuggets y aros de cebolla', items:[
    {name:'Patatas fritas', desc:'', price:'3,00', priceG:'4,00'},
    {name:'Patatas bravas o deluxe', desc:'', price:'4,50', priceG:'5,50'},
    {name:'Döner box', desc:'Carne de pollo o ternera con patatas', price:'4,00', priceG:'5,00'},
    {name:'Roquetas (6 uds.)', desc:'', price:'6,00', priceMenu:'7,50'},
    {name:'Alitas de pollo (6 uds.)', desc:'', price:'6,00', priceMenu:'7,50'},
    {name:'Falafel (6 uds.)', desc:'', price:'5,00', priceMenu:'7,00'},
    {name:'Nuggets de pollo (6 uds.)', desc:'', price:'6,00', priceMenu:'7,50'},
    {name:'Taco', desc:'', price:'8,00', priceMenu:'10,00'},
    {name:'Plato gratinado', desc:'', price:'7,00', priceMenu:'9,00'},
    {name:'Finger de pollo (6 uds.)', desc:'', price:'6,00', priceMenu:'7,50'},
    {name:'Finger de queso (6 uds.)', desc:'', price:'6,00', priceMenu:'7,50'},
    {name:'Aros de cebolla', desc:'', price:'6,00', priceMenu:'7,50'},
    {name:'Jalapeños', desc:'', price:'6,00', priceMenu:'7,50'},
    {name:'Calamares', desc:'', price:'7,00', priceMenu:'7,50'},
    {name:'Dürüm gratinado', desc:'', price:'7,00', priceMenu:'9,00'},
  ]},
  { key:'bebidas', label:'Bebidas', items:[
    {name:'Refresco 33cl', desc:'', price:'1,50'},
    {name:'Refresco 1L', desc:'', price:'2,50'},
    {name:'Refresco 2L', desc:'', price:'3,00'},
    {name:'Bebidas latino', desc:'Pony Malta y similares', note:'Consultar precio'},
  ]},
];
